Document dcc_dropdown and dcc_slider
plotly/dash-julia-docs pull request #2
Opened 2021-05-26 19:40 UTC by jdamiba

The purpose of this PR is to begin the process of documenting the Dash Core Components in the Dash for Julia User Guide. 

This process starts with the Dropdown and Slider components. 

Link to visit: 

- homepage -> new "Open Source Components" section 
- /dash_core_components -> Index page
- /dash_core_components/dropdown -> dropdown page
- /dash_core_components/slider -> slider page

2021-05-27 02:28 UTC, jackparmer requested changes
Just some cleanup notes - comment lines that were committed, some variable acmes that I think could be improved, and inconsistent newline spacing.

2021-05-27 02:28 UTC, jackparmer commented on dash_docs/chapters/dash_core_components/Dropdown/examples/clearable.jl
> +
consistent spacing - 1 newline instead of 2

2021-05-27 02:28 UTC, jackparmer commented on dash_docs/chapters/dash_core_components/Dropdown/examples/default.jl
> +
spacing (1 newline instead of 2)

2021-05-27 02:28 UTC, jackparmer commented on dash_docs/chapters/dash_core_components/Dropdown/examples/disabled_options.jl
> +
spacing

2021-05-27 02:28 UTC, jackparmer commented on dash_docs/chapters/dash_core_components/Dropdown/examples/dynamic_options.jl
> +    #html_label(["Multi Dynamic Dropdown", dcc_dropdown(id="demo-dropdown-3", multi=true) ])
Can we delete this? What was this comment left?

2021-05-27 02:28 UTC, jackparmer commented on dash_docs/chapters/dash_core_components/Dropdown/examples/dynamic_options.jl
> +# callback!(
delete comment block

2021-05-27 02:28 UTC, jackparmer commented on dash_docs/chapters/dash_core_components/Dropdown/examples/multi.jl
> +
spacing

2021-05-27 02:28 UTC, jackparmer commented on dash_docs/chapters/dash_core_components/Dropdown/examples/placeholder.jl
> +
spacing

2021-05-27 02:28 UTC, jackparmer commented on dash_docs/chapters/dash_core_components/Dropdown/examples/searchable.jl
> +
spacing

2021-05-27 02:28 UTC, jackparmer commented on dash_docs/chapters/dash_core_components/Dropdown/index.jl
> +
inconsistent  number of newlines

2021-05-27 02:28 UTC, jackparmer commented on dash_docs/chapters/dash_core_components/Dropdown/index.jl
> +dropdown2 = LoadExampleCode(string(examples_path, "/default.jl"))
Maybe a way to make assign dropdown's 2-9 this more DRY?

2021-05-27 02:28 UTC, jackparmer commented on dash_docs/chapters/dash_core_components/Slider/examples/basic_slider.jl
> +
newline

2021-05-27 02:28 UTC, jackparmer commented on dash_docs/chapters/dash_core_components/Slider/examples/marks_steps.jl
> +
newline

2021-05-27 02:28 UTC, jackparmer commented on dash_docs/chapters/dash_core_components/Slider/index.jl
> +slider1 = LoadExampleCode(string(examples_path, "/basic_slider.jl"))
DRY or more specific naming (eg I think basic_slider and multi_slider would be preferable to slider1 and slider2)

2021-05-27 02:28 UTC, jackparmer commented on dash_docs/chapters/dash_core_components/index.jl
> +    # html_h3("RangeSlider"),
Delete comments please

2021-05-27 02:28 UTC, jackparmer commented on run.jl
> +#include("dash_docs/chapters/whats_dash/introduction.jl");
delete comments

2021-06-09 14:01 UTC, waralex approved these changes
looks good to me

2021-06-10 17:56 UTC, merged